# getx_network_call_with_exceptione_handle